[package]
name = "sus"
version = "0.1.0"
authors = ["Brian Schwind <brianmschwind@gmail.com>"]
edition = "2018"

[[bin]]
name = "client"
path = "src/main.rs"

[[bin]]
name = "server"
path = "src/server/main.rs"

[dependencies]
futures = "0.3.7"
wgpu = "0.6.0"
winit = "0.23.0"